run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    # Enabled by default
    - errcheck      # Check for unchecked errors
    - govet         # Go vet examinations
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced static analysis
    - unused        # Check for unused constants, variables, functions

    # Additional recommended linters
    - misspell      # Spell checker
    - revive        # Fast, extensible, flexible linter
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Find unused function parameters
    - gosec         # Security issues
    - bodyclose     # Check HTTP response body is closed
    - gocritic      # Opinionated linter
    - gocyclo       # Cyclomatic complexity
    - dupl          # Code duplication
    - prealloc      # Slice preallocation

linters-settings:
  gocyclo:
    min-complexity: 15  # Warn on functions with cyclomatic complexity > 15

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - commentFormatting  # Allow flexible comment styles

  revive:
    rules:
      - name: exported
        disabled: false
      - name: package-comments
        disabled: false
      - name: var-naming
        disabled: false

  misspell:
    locale: US

  gosec:
    excludes:
      - G204  # Subprocess launched with variable - common in CLI tools
      - G304  # File path from variable - necessary for file operations

  dupl:
    threshold: 100  # Minimum token sequence for duplication detection

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

    # Exclude known issues in specific files
    - path: cmd/my-context/main.go
      linters:
        - gocyclo

  max-issues-per-linter: 0
  max-same-issues: 0

  # Don't hide multiple occurrences of same issue
  new: false
